# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVG3wO6E4yz6iGVMMXUqD6v4rDNc4lOy
"""

import streamlit as st
import numpy as np
import cv2
import matplotlib.pyplot as plt
import re
import pytesseract
from pytesseract import Output
from skimage.filters import threshold_local
from PIL import Image
import pandas as pd
from datetime import datetime
import os
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
import io
import tempfile

# Constants
MASTER_EXCEL_FILE = "hotel_bills_database.xlsx"
MODEL_FILE = "hotel_bill_processor_model.pkl"

# Page configuration
st.set_page_config(
    page_title="Hotel Bill Processor",
    page_icon="🏨",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1f77b4;
        text-align: center;
        margin-bottom: 2rem;
    }
    .success-box {
        padding: 1rem;
        border-radius: 0.5rem;
        background-color: #d4edda;
        border: 1px solid #c3e6cb;
        color: #155724;
        margin: 1rem 0;
    }
    .info-box {
        padding: 1rem;
        border-radius: 0.5rem;
        background-color: #d1ecf1;
        border: 1px solid #bee5eb;
        color: #0c5460;
        margin: 1rem 0;
    }
    </style>
""", unsafe_allow_html=True)

def load_and_preprocess_image(image_file):
    """Load and preprocess the image"""
    # Convert uploaded file to numpy array
    file_bytes = np.asarray(bytearray(image_file.read()), dtype=np.uint8)
    image = cv2.imdecode(file_bytes, cv2.IMREAD_COLOR)

    if image is None:
        raise ValueError("Could not load image")

    # Convert to RGB
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Resize if too large
    height, width = image.shape[:2]
    if height > 2000 or width > 2000:
        scale = min(2000/height, 2000/width)
        new_width = int(width * scale)
        new_height = int(height * scale)
        image = cv2.resize(image, (new_width, new_height), interpolation=cv2.INTER_AREA)

    return image

def enhance_image_quality(image):
    """Enhanced image quality improvement"""
    gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
    denoised = cv2.medianBlur(gray, 3)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    contrast_enhanced = clahe.apply(denoised)
    T = threshold_local(contrast_enhanced, 15, offset=12, method="gaussian")
    binary = (contrast_enhanced > T).astype("uint8") * 255
    kernel = np.ones((2,2), np.uint8)
    binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)
    binary = cv2.morphologyEx(binary, cv2.MORPH_OPEN, kernel)
    return binary, contrast_enhanced, gray

def extract_text_from_image(image):
    """Extract text using OCR"""
    configs = [
        r'--oem 3 --psm 6',
        r'--oem 3 --psm 4',
        r'--oem 3 --psm 3',
    ]

    best_text = ""
    for config in configs:
        try:
            text = pytesseract.image_to_string(image, config=config)
            if len(text) > len(best_text):
                best_text = text
        except:
            continue

    return best_text

def extract_hotel_info(text):
    """Extract hotel name and address"""
    lines = [line.strip() for line in text.split('\n') if line.strip()]
    hotel_name = ""
    address = ""
    address_lines = []

    hotel_patterns = [
        r'^[A-Z][A-Za-z\s&\.\-]{3,}(?:Hotel|Resort|Inn|Suites|Lodge|Motel|Plaza)$',
        r'^(?!.*(?:invoice|bill|receipt|date|total|tax|room|guest))[A-Z][A-Za-z\s&\.\-]{3,}$'
    ]

    for i, line in enumerate(lines[:10]):
        for pattern in hotel_patterns:
            if re.match(pattern, line, re.IGNORECASE):
                if not hotel_name:
                    hotel_name = line
                    break

        if hotel_name and i > (lines.index(hotel_name) if hotel_name in lines else 0):
            if re.search(r'\d+[\sA-Za-z]+,?[\sA-Za-z]+,?[\sA-Za-z]+', line):
                address_lines.append(line)

    address = ' '.join(address_lines[:3])
    return hotel_name, address

def extract_dates(text):
    """Extract check-in and check-out dates"""
    date_patterns = [
        r'\b(0?[1-9]|1[0-2])[/-](0?[1-9]|[12][0-9]|3[01])[/-](\d{4}|\d{2})\b',
        r'\b(0?[1-9]|[12][0-9]|3[01])[-/](0?[1-9]|1[0-2])[-/](\d{4}|\d{2})\b',
        r'\b(0?[1-9]|1[0-2]|0?[1-9]|[12][0-9]|3[01])\s+(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4}\b',
        r'\b(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(0?[1-9]|[12][0-9]|3[01]),?\s+\d{4}\b',
    ]

    dates = []
    for pattern in date_patterns:
        found_dates = re.findall(pattern, text, re.IGNORECASE)
        for date_match in found_dates:
            if isinstance(date_match, tuple):
                date_str = ' '.join([str(part) for part in date_match if part])
                dates.append(date_str)
            else:
                dates.append(date_match)

    seen = set()
    unique_dates = []
    for date in dates:
        if date not in seen:
            seen.add(date)
            unique_dates.append(date)

    check_in = unique_dates[0] if len(unique_dates) > 0 else ""
    check_out = unique_dates[1] if len(unique_dates) > 1 else ""
    return check_in, check_out

def extract_guest_info(text):
    """Extract guest name and room number"""
    guest_name = ""
    room_number = ""

    guest_patterns = [
        r'(?:Guest|Name|Customer|Passenger)\s*:?\s*([A-Z][a-zA-Z]+(?:\s+[A-Z][a-zA-Z\.]+)+)',
        r'(?:Guest Name|Customer Name)\s*:?\s*([A-Z][a-zA-Z]+\s+[A-Z][a-zA-Z]+)',
    ]

    for pattern in guest_patterns:
        matches = re.findall(pattern, text, re.IGNORECASE)
        if matches:
            guest_name = max(matches, key=len)
            break

    room_patterns = [
        r'(?:Room|Rm)\.?\s*(?:No|Number|#)?\.?\s*:?\s*([A-Z]?\d+[A-Z]?)',
    ]

    for pattern in room_patterns:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            room_number = match.group(1)
            break

    return guest_name, room_number

def extract_line_items(text):
    """Extract line items"""
    items = []
    lines = text.split('\n')

    item_patterns = [
        r'^([A-Za-z][A-Za-z\s\-&]+?)\s+([\$€£]?\s?\d{1,3}(?:[,.]\d{3})*\.?\d{0,2})$',
        r'^([A-Za-z][A-Za-z\s\-&]+?)\s+([\$€£]?\s?\d+\.\d{2})$',
    ]

    exclude_keywords = ['total', 'subtotal', 'tax', 'vat', 'gst', 'balance', 'amount due']

    for line in lines:
        line = line.strip()
        if any(keyword in line.lower() for keyword in exclude_keywords):
            continue
        if len(line) < 4:
            continue

        for pattern in item_patterns:
            match = re.search(pattern, line)
            if match:
                description = match.group(1).strip()
                amount_str = match.group(2).strip()
                amount_clean = re.sub(r'[^\d.]', '', amount_str)

                if len(description) > 2 and description[0].isalpha():
                    try:
                        amount_float = float(amount_clean)
                        if 0.01 <= amount_float <= 10000:
                            items.append({
                                'description': description,
                                'amount': amount_float
                            })
                            break
                    except ValueError:
                        continue

    return items

def extract_totals(text):
    """Extract financial totals"""
    subtotal = 0.0
    tax = 0.0
    total = 0.0

    patterns = {
        'subtotal': [r'(?:Sub\s*Total|Subtotal)\s*:?\s*[\$€£]?\s*(\d{1,3}(?:[,.]\d{3})*\.?\d{0,2})'],
        'tax': [r'(?:Tax|GST|VAT)\s*:?\s*[\$€£]?\s*(\d{1,3}(?:[,.]\d{3})*\.?\d{0,2})'],
        'total': [r'(?:Total|Grand\s*Total|Amount\s*Due)\s*:?\s*[\$€£]?\s*(\d{1,3}(?:[,.]\d{3})*\.?\d{0,2})']
    }

    for key, pattern_list in patterns.items():
        for pattern in pattern_list:
            matches = re.findall(pattern, text, re.IGNORECASE)
            if matches:
                value_str = matches[-1].replace(',', '').replace(' ', '')
                try:
                    value_float = float(value_str)
                    if key == 'subtotal':
                        subtotal = value_float
                    elif key == 'tax':
                        tax = value_float
                    elif key == 'total':
                        total = value_float
                except ValueError:
                    continue

    return subtotal, tax, total

def extract_invoice_number(text):
    """Extract invoice number"""
    patterns = [
        r'(?:Invoice|Bill|Receipt)\s*(?:No|Number|#)?\.?\s*:?\s*([A-Z0-9\-/#]+)',
        r'(?:Folio|Confirmation)\s*(?:No|Number|#)?\.?\s*:?\s*([A-Z0-9\-/#]+)',
    ]

    for pattern in patterns:
        matches = re.findall(pattern, text, re.IGNORECASE)
        if matches:
            return matches[0]

    return ""

class HotelBillProcessor:
    """Model class to handle hotel bill processing"""

    def __init__(self):
        self.vectorizer = TfidfVectorizer(max_features=1000)
        self.processed_data = []
        self.model_version = "1.0"
        self.is_fitted = False

    def load_existing_model(self, model_file):
        """Load existing model"""
        try:
            with open(model_file, 'rb') as f:
                model_data = pickle.load(f)
            self.vectorizer = model_data['vectorizer']
            self.processed_data = model_data['processed_data']
            self.model_version = model_data['model_version']
            self.is_fitted = model_data.get('is_fitted', False)
            return True
        except:
            return False

    def fit(self, texts):
        """Fit the vectorizer"""
        if texts:
            try:
                self.vectorizer.fit(texts)
                self.is_fitted = True
            except:
                pass

    def add_data(self, hotel_name, raw_text, image_name):
        """Add new data"""
        self.processed_data.append({
            'hotel_name': hotel_name,
            'raw_text': raw_text,
            'image_name': image_name,
            'timestamp': datetime.now()
        })

    def save_model(self):
        """Save the model"""
        model_data = {
            'vectorizer': self.vectorizer,
            'processed_data': self.processed_data,
            'model_version': self.model_version,
            'is_fitted': self.is_fitted,
            'timestamp': datetime.now()
        }

        with open(MODEL_FILE, 'wb') as f:
            pickle.dump(model_data, f)

        return MODEL_FILE

def process_hotel_bill(image_file, processor=None):
    """Main processing function"""
    original_image = load_and_preprocess_image(image_file)
    binary_image, contrast_enhanced, gray_image = enhance_image_quality(original_image)

    text_binary = extract_text_from_image(binary_image)
    text_contrast = extract_text_from_image(contrast_enhanced)
    text_gray = extract_text_from_image(gray_image)

    texts = [text_binary, text_contrast, text_gray]
    final_text = max(texts, key=len)

    hotel_name, address = extract_hotel_info(final_text)
    check_in, check_out = extract_dates(final_text)
    guest_name, room_number = extract_guest_info(final_text)
    invoice_number = extract_invoice_number(final_text)
    line_items = extract_line_items(final_text)
    subtotal, tax, total = extract_totals(final_text)

    if processor:
        processor.add_data(hotel_name, final_text, image_file.name)

    return {
        'hotel_name': hotel_name,
        'address': address,
        'invoice_number': invoice_number,
        'guest_name': guest_name,
        'room_number': room_number,
        'check_in_date': check_in,
        'check_out_date': check_out,
        'line_items': line_items,
        'subtotal': subtotal,
        'tax': tax,
        'total': total,
        'raw_text': final_text,
        'processing_date': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'image_filename': image_file.name,
        'images': {
            'original': original_image,
            'gray': gray_image,
            'contrast': contrast_enhanced,
            'binary': binary_image
        }
    }

def append_to_master_excel(result, excel_file=None):
    """Append to Excel file"""
    summary_record = {
        'Processing Date': result['processing_date'],
        'Hotel Name': result['hotel_name'],
        'Address': result['address'],
        'Guest Name': result['guest_name'],
        'Room Number': result['room_number'],
        'Invoice Number': result['invoice_number'],
        'Check-in Date': result['check_in_date'],
        'Check-out Date': result['check_out_date'],
        'Subtotal': result['subtotal'],
        'Tax': result['tax'],
        'Total Amount': result['total'],
        'Image Filename': result['image_filename']
    }

    line_items_records = []
    for item in result['line_items']:
        line_items_records.append({
            'Processing Date': result['processing_date'],
            'Hotel Name': result['hotel_name'],
            'Guest Name': result['guest_name'],
            'Invoice Number': result['invoice_number'],
            'Description': item['description'],
            'Amount': item['amount']
        })

    if excel_file and os.path.exists(excel_file):
        try:
            existing_summary = pd.read_excel(excel_file, sheet_name='All Bills Summary')
            existing_items = pd.read_excel(excel_file, sheet_name='All Line Items')
        except:
            existing_summary = pd.DataFrame()
            existing_items = pd.DataFrame()

        new_summary_df = pd.DataFrame([summary_record])
        updated_summary = pd.concat([existing_summary, new_summary_df], ignore_index=True)

        if line_items_records:
            new_items_df = pd.DataFrame(line_items_records)
            updated_items = pd.concat([existing_items, new_items_df], ignore_index=True)
        else:
            updated_items = existing_items
    else:
        updated_summary = pd.DataFrame([summary_record])
        updated_items = pd.DataFrame(line_items_records) if line_items_records else pd.DataFrame()

    with pd.ExcelWriter(MASTER_EXCEL_FILE, engine='openpyxl') as writer:
        updated_summary.to_excel(writer, sheet_name='All Bills Summary', index=False)

        if not updated_items.empty:
            updated_items.to_excel(writer, sheet_name='All Line Items', index=False)
        else:
            pd.DataFrame({'Processing Date': [], 'Hotel Name': [], 'Guest Name': [],
                         'Invoice Number': [], 'Description': [], 'Amount': []}).to_excel(
                writer, sheet_name='All Line Items', index=False)

    return MASTER_EXCEL_FILE

# Main Streamlit App
def main():
    st.markdown('<div class="main-header">🏨 Hotel Bill Processing System</div>', unsafe_allow_html=True)

    # Sidebar
    with st.sidebar:
        st.header("📁 Upload Existing Files")
        st.info("Upload previous database/model files to append new data")

        uploaded_excel = st.file_uploader("Upload Database (.xlsx)", type=['xlsx'])
        uploaded_model = st.file_uploader("Upload Model (.pkl)", type=['pkl'])

        if uploaded_excel:
            with open(MASTER_EXCEL_FILE, 'wb') as f:
                f.write(uploaded_excel.getbuffer())
            st.success("✅ Database loaded!")

        if uploaded_model:
            with open(MODEL_FILE, 'wb') as f:
                f.write(uploaded_model.getbuffer())
            st.success("✅ Model loaded!")

        st.markdown("---")
        st.header("ℹ️ About")
        st.write("This app processes hotel bills using OCR and extracts structured data.")

    # Initialize processor
    if 'processor' not in st.session_state:
        st.session_state.processor = HotelBillProcessor()
        if os.path.exists(MODEL_FILE):
            st.session_state.processor.load_existing_model(MODEL_FILE)

    # Main content
    tab1, tab2, tab3 = st.tabs(["📤 Upload & Process", "📊 View Database", "📥 Download Files"])

    with tab1:
        st.header("Upload Hotel Bill Images")
        uploaded_files = st.file_uploader(
            "Choose hotel bill images",
            type=['png', 'jpg', 'jpeg', 'tiff', 'bmp'],
            accept_multiple_files=True
        )

        if uploaded_files:
            if st.button("🚀 Process All Bills", type="primary"):
                progress_bar = st.progress(0)
                all_results = []

                for idx, uploaded_file in enumerate(uploaded_files):
                    st.subheader(f"Processing: {uploaded_file.name}")

                    try:
                        with st.spinner(f"Processing {uploaded_file.name}..."):
                            # Reset file pointer
                            uploaded_file.seek(0)
                            result = process_hotel_bill(uploaded_file, st.session_state.processor)
                            all_results.append(result)

                            # Display results
                            col1, col2 = st.columns(2)

                            with col1:
                                st.markdown("### 📋 Extracted Information")
                                st.write(f"**Hotel:** {result['hotel_name'] or 'Not found'}")
                                st.write(f"**Address:** {result['address'] or 'Not found'}")
                                st.write(f"**Guest:** {result['guest_name'] or 'Not found'}")
                                st.write(f"**Room:** {result['room_number'] or 'Not found'}")
                                st.write(f"**Invoice:** {result['invoice_number'] or 'Not found'}")
                                st.write(f"**Check-in:** {result['check_in_date'] or 'Not found'}")
                                st.write(f"**Check-out:** {result['check_out_date'] or 'Not found'}")

                                st.markdown("### 💰 Financial Summary")
                                if result['subtotal']:
                                    st.write(f"**Subtotal:** ${result['subtotal']:.2f}")
                                if result['tax']:
                                    st.write(f"**Tax:** ${result['tax']:.2f}")
                                if result['total']:
                                    st.write(f"**Total:** ${result['total']:.2f}")

                            with col2:
                                st.markdown("### 🖼️ Processed Images")
                                img_tab1, img_tab2, img_tab3, img_tab4 = st.tabs(["Original", "Grayscale", "Contrast", "Binary"])

                                with img_tab1:
                                    st.image(result['images']['original'], use_container_width=True)
                                with img_tab2:
                                    st.image(result['images']['gray'], use_container_width=True)
                                with img_tab3:
                                    st.image(result['images']['contrast'], use_container_width=True)
                                with img_tab4:
                                    st.image(result['images']['binary'], use_container_width=True)

                            # Line items
                            if result['line_items']:
                                st.markdown("### 📦 Line Items")
                                items_df = pd.DataFrame(result['line_items'])
                                st.dataframe(items_df, use_container_width=True)

                            # Append to Excel
                            append_to_master_excel(result, MASTER_EXCEL_FILE if os.path.exists(MASTER_EXCEL_FILE) else None)

                            st.success(f"✅ Successfully processed {uploaded_file.name}")
                            st.markdown("---")

                    except Exception as e:
                        st.error(f"❌ Error processing {uploaded_file.name}: {str(e)}")

                    progress_bar.progress((idx + 1) / len(uploaded_files))

                # Save model
                if all_results:
                    all_texts = [result['raw_text'] for result in all_results]
                    if st.session_state.processor.processed_data:
                        existing_texts = [data['raw_text'] for data in st.session_state.processor.processed_data]
                        all_texts = existing_texts + all_texts

                    st.session_state.processor.fit(all_texts)
                    st.session_state.processor.save_model()

                    st.markdown('<div class="success-box">✅ All bills processed and saved successfully!</div>', unsafe_allow_html=True)

    with tab2:
        st.header("Database Overview")

        if os.path.exists(MASTER_EXCEL_FILE):
            try:
                summary_df = pd.read_excel(MASTER_EXCEL_FILE, sheet_name='All Bills Summary')
                items_df = pd.read_excel(MASTER_EXCEL_FILE, sheet_name='All Line Items')

                st.subheader(f"📊 Total Bills: {len(summary_df)}")

                col1, col2, col3 = st.columns(3)
                with col1:
                    st.metric("Total Bills", len(summary_df))
                with col2:
                    total_amount = summary_df['Total Amount'].sum()
                    st.metric("Total Amount", f"${total_amount:,.2f}")
                with col3:
                    st.metric("Total Line Items", len(items_df))

                st.subheader("All Bills Summary")
                st.dataframe(summary_df, use_container_width=True)

                st.subheader("All Line Items")
                st.dataframe(items_df, use_container_width=True)

            except Exception as e:
                st.error(f"Error loading database: {str(e)}")
        else:
            st.info("No database found. Process some bills first!")

    with tab3:
        st.header("Download Processed Files")

        col1, col2 = st.columns(2)

        with col1:
            if os.path.exists(MASTER_EXCEL_FILE):
                with open(MASTER_EXCEL_FILE, 'rb') as f:
                    st.download_button(
                        label="📥 Download Database (Excel)",
                        data=f,
                        file_name=MASTER_EXCEL_FILE,
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    )
            else:
                st.info("No database file available yet")

        with col2:
            if os.path.exists(MODEL_FILE):
                with open(MODEL_FILE, 'rb') as f:
                    st.download_button(
                        label="📥 Download Model (PKL)",
                        data=f,
                        file_name=MODEL_FILE,
                        mime="application/octet-stream"
                    )
            else:
                st.info("No model file available yet")

        st.markdown("---")
        st.markdown('<div class="info-box">💡 <b>Tip:</b> Keep both files for future sessions to append new data!</div>', unsafe_allow_html=True)

if __name__ == "__main__":
    main()